In [5]:
import torch
import pyaudio
import numpy as np
import speech_recognition as sr

In [7]:
listener = sr.Recognizer()  
instruction = ""
try:
     with sr.Microphone() as src:
        print("LISTENING ...")
        speech = listener.listen(src)
        print(speech)
        instruction += listener.recognize_google(speech)
        print(instruction)
except Exception as e:
    print(e)
    pass

LISTENING ...
recognition connection failed: [Errno 11001] getaddrinfo failed


In [14]:
speech.frame_data

b'\xf1\xff\xf2\xff\xfa\xff\xfe\xff\xf7\xff\xfc\xff\xf9\xff\xf7\xff\xff\xff\x02\x00\x07\x00\x08\x00\x03\x00\x04\x00\r\x00\x11\x00\x0f\x00\x0e\x00\x0b\x00\x04\x00\x00\x00\x00\x00\xf6\xff\xf3\xff\xf5\xff\xec\xff\xef\xff\xf2\xff\xf3\xff\xf0\xff\xf3\xff\xf8\xff\xfa\xff\xf8\xff\xfd\xff\xfc\xff\xfe\xff\x06\x00\x0b\x00\r\x00\n\x00\x0e\x00\t\x00\x0e\x00\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x05\x00\x04\x00\x03\x00\xfb\xff\xf9\xff\xfa\xff\xf7\xff\xf9\xff\xf6\xff\xef\xff\xf2\xff\xf1\xff\xf2\xff\xf2\xff\xf9\xff\xf8\xff\xfe\xff\x05\x00\x07\x00\t\x00\n\x00\n\x00\x07\x00\x06\x00\x01\x00\x01\x00\xff\xff\xfb\xff\xf9\xff\xf7\xff\xf2\xff\xf0\xff\xee\xff\xe8\xff\xe1\xff\xe0\xff\xdc\xff\xdd\xff\xe4\xff\xe6\xff\xea\xff\xed\xff\xf2\xff\xf4\xff\xf9\xff\x02\x00\x05\x00\x03\x00\n\x00\t\x00\x11\x00\x1c\x00\x1b\x00\x17\x00\x12\x00\x12\x00\x11\x00\x14\x00\x10\x00\x10\x00\x11\x00\x13\x00\x12\x00\x13\x00\x17\x00\x1a\x00\x1e\x00\x1e\x00\x1e\x00\x1d\x00!\x00!\x00(\x00(\x00#\x00#\x00*\x00%\x00\x1d\x00\x15\x00

In [4]:
audio_data = speech.get_wav_data()
data_s16 = np.frombuffer(audio_data,dtype=np.int16,count=len(audio_data)//2,offset=0)
data_s16

array([18770, 17990,  6808, ...,     1,    -3,   -30], dtype=int16)

In [5]:
len(data_s16) / speech.sample_rate

7.5849433106575965

In [12]:
def record_audio(chunk=1024,format=pyaudio.paInt16,channel=1,rate=16_000,record_seconds=2):
    """
    Records audio from the microphone and return numpy array
    Args:
        chunk: size of audio data to read per chunk
        format: audio format 
        channels: number of audio channels (mono)
        rate: sampling rate (defualts to mms)
        record_seconds: duration of recording in seconds
    """
    p = pyaudio.PyAudio()
    # Open audio stream for recording
    stream = p.open(
        format=format,
        channels=channel,
        rate=rate,
        input=True,
        frames_per_buffer=chunk
    )
    frames = []
    for _ in range(0 , int(rate / chunk * record_seconds)):
        data = stream.read(chunk)
        frames.append(data)

    # stop and close the stream
    stream.stop_stream()
    stream.close()
    # close pyaudio
    p.terminate()
    # Combine the recorded chunks into a single byte array
    audio_data = b''.join(frames)
    audio_array = np.frombuffer(audio_data,dtype=np.int16)
    return audio_array


In [7]:
x = np.random.random((3,2))

In [10]:
torch.tensor(x)

tensor([[0.0313, 0.8926],
        [0.4577, 0.1214],
        [0.5222, 0.1763]], dtype=torch.float64)

In [13]:
record_audio()

array([ 0,  0, -1, ..., 81, 83, 82], dtype=int16)

In [1]:
import os

In [2]:
api_key = os.environ.get("GEMINI_API_KEY")

In [3]:
api_key

'AIzaSyCHIt0htsxDFw5vVmbg39BUE58K-mBWD0g'

In [1]:
prompt = "hello there"

In [2]:
any(keyword in prompt.strip("") for keyword in ["hello", "hi", "good morning"])

True

In [1]:
from pydub import AudioSegment

In [3]:
audio = AudioSegment.from_file("response.wav")

In [4]:
audio.duration_seconds

43.272